### PR TITLE
Move public host check inside create session flow

### PR DESCRIPTION
**Pull request by Nipher**
Issue: https://www.notion.so/29k/Closed-BETA-0055aabd797b40c7b390b7cea4eba658#10d6f31782a34cd38a0bf69ced519684

#### Screenshots

| Before | After |
|-|-|
| Screenshot_1667236896 |  Screenshot_1667241872 |

"Pick flow" screen (UX / UI Needed, will point it out [in notion and ask for help](https://www.notion.so/29k/Closed-BETA-0055aabd797b40c7b390b7cea4eba658#520dd6b731cf49d4b1f9ce9db7b8b5be))

And normal users get `private` session type by behind the scenes:
https://github.com/29ki/29k/blob/088bfb0ff117a5c0a8c5550813a0a7be4667a0e7/client/src/routes/Sessions/components/CreateSessionModal.tsx#L269-L271

### Verification Process

- Use the app as a anonymous user, see if you can create a private session only.
- Use the app as a host, see if you can choose between public and private sessions on the creation flow.

### CODE REVIEW

**Comment by gewfy** [comment]
Hmm are we sure this is the intended flow? Shouldn't public hosts be able to choose to create public och private?

**Review by swemail — APPROVED** [review]

**Review by gewfy — CHANGES_REQUESTED** [review]
Hmm are we sure this is the intended flow? Shouldn't public hosts be able to choose to create public och private?

**Comment by Nipher** [comment]
@gewfy public hosts are able to choose, yes.

**Comment by Nipher** [comment]
@gewfy https://github.com/29ki/29k/blob/fe0fdc34c8e0e9fe78f7766132ee085a0cdb1bbf/client/src/routes/Sessions/components/CreateSessionModal.tsx#L260

**Review by gewfy — APPROVED** [review]
Oh sorry completely misunderstood the logic 👌

**Pull request merged**
